skills_list = ['Achievement Orientation',
 'Active Listening',
 'Adaptability',
 'Agility',
 'Analytical Thinking',
 'Appreciate Others',
 'Approachability',
 'Assertiveness',
 'Attracting Talent',
 'Authenticity',
 'Balance',
 'Body Language',
 'Building Effective Teams',
 'Business Acumen',
 'Business Cultural Insight',
 'Charismatic Leadership',
 'Collaboration',
 'Communicate Effectively',
 'Compassion',
 'Competitive',
 'Composure',
 'Conceptual Thinking',
 'Connecting With Others',
 'Conscientiousness',
 'Consciousness',
 'Contagious Spirit',
 'Contributing to Society',
 'Cooperation',
 'Courage',
 'Creativity',
 'Cross-Cultural Engagement',
 'Customer Focus',
 'Decision Making',
 'Delegation',
 'Dependability',
 'Detail Orientation',
 'Direction Setting',
 'Driving Engagement',
 'Driving for Results',
 'Driving Vision & Purpose',
 'Emotional Intelligence',
 'Empathy',
 'Empowerment',
 'Energy Levels',
 'Engaging Employees',
 'Engaging with Others ',
 'Finding Purpose and Passion',
 'Generate Enthusiasm',
 'Global Mindset',
 'Goal Setting ',
 'Holding People Accountable ',
 'Humility',
 'Humor',
 'Impact through Influence',
 'Innovation',
 'Integrity',
 'Interpersonal Understanding',
 'Leveraging Networks',
 'Managing Ambiguity',
 'Managing Change',
 'Managing Complexity',
 'Managing Conflict',
 'Managing Diversity',
 'Managing Media and PR',
 'Managing Social Media',
 'Managing Talent',
 'Managing Upward',
 'Market Focused',
 'Mindfulness ',
 'Motivating Others',
 'Negotiation',
 'Network Building',
 'Nimble Learning',
 'Opportunistic',
 'Oral Communication',
 'Organizational Awareness',
 'Patience',
 'Peer Relationships',
 'Perseverance',
 'Persuasion',
 'Planning & Organizing',
 'Poise',
 'Presentation Skills',
 'Problem Solving',
 'Process Management ',
 'Providing Feedback',
 'Public speaking ',
 'Relationship Building',
 'Resilience',
 'Resource Management',
 'Resourcefulness',
 'Self Awareness',
 'Self Confidence',
 'Self Development',
 'Situational Leadership',
 'Soliciting Team Input',
 'Spirituality',
 'Stakeholder Management',
 'Stakeholder Savvy',
 'Strategic Planning',
 'Stress Tolerance',
 'Systems Thinking',
 'Taking Initiative',
 'Taking on Tough Situations',
 'Teamwork',
 'Time Management',
 'Trustworthiness  ',
 'Values Alignment',
 'Walk the Talk ',
 'Work Life balance',
 'Encouraging Work Life Balance',
 'Written Communication',
 'Engaging with Others',
 'Goal Setting',
 'Mindfulness',
 'Process Management',
 'Public speaking',
 'Holding People Accountable'
 ]

get_action_response_format = {
  "actions": [
    "Provide 3 concise action steps to complete the task.(9-10 words)",
    "Provide 3 concise action steps to complete the task.(9-10 words)",
    "Provide 3 concise action steps to complete the task.(9-10 words)"
  ]
}

get_action_skills = {
  "Skills": [
    "Provide matchings skills here"
  ]
}