import type { Lead } from "@/types/crm";

export const INITIAL_STATUSES = [
  "Prospects",
  "Contacted",
  "Qualified",
  "Proposal",
  "Negotiation",
  "Won",
];

export const STATUS_COLORS: Record<string, string> = {
  Prospects: "bg-blue-50 dark:bg-blue-950",
  Contacted: "bg-purple-50 dark:bg-purple-950",
  Qualified: "bg-green-50 dark:bg-green-950",
  Proposal: "bg-orange-50 dark:bg-orange-950",
  Negotiation: "bg-yellow-50 dark:bg-yellow-950",
  Won: "bg-emerald-50 dark:bg-emerald-950",
};

export const CHANNEL_STYLES: Record<string, string> = {
  Email: "bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300",
  Phone: "bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300",
  LinkedIn: "bg-blue-200 dark:bg-blue-800 text-blue-800 dark:text-blue-200",
  "In-Person": "bg-purple-100 dark:bg-purple-900 text-purple-700 dark:text-purple-300",
  Chat: "bg-cyan-100 dark:bg-cyan-900 text-cyan-700 dark:text-cyan-300",
  Website: "bg-orange-100 dark:bg-orange-900 text-orange-700 dark:text-orange-300",
};

export const SAMPLE_LEADS: Lead[] = [
  {
    id: "L001",
    firstName: "Hannah",
    lastName: "Brooks",
    name: "Hannah Brooks",
    avatar: "#fae8ff",
    email: "hannah.brooks@figma.com",
    phone: "+1-650-932-5512",
    linkedinUrl: "https://linkedin.com/in/hannahbrooks",
    company: "Figma",
    companySize: "500-1,000",
    industry: "Design SaaS",
    companyLocation: "San Francisco, USA",
    status: "Qualified",
    pipeline: "Enterprise",
    priority: "Medium",
    dealValue: 68000,
    currency: "USD",
    leadScore: 79,
    probability: 55,
    source: "LinkedIn Outreach",
    channels: ["LinkedIn"],
    lastActivityAt: new Date("2024-07-02"),
    nextFollowupAt: new Date("2024-07-05"),
    tags: ["Enterprise", "Design", "High Intent"],
    createdAt: new Date("2024-07-03"),
  },
  {
    id: "L002",
    firstName: "Rishi",
    lastName: "Malhotra",
    name: "Rishi Malhotra",
    avatar: "#a5f3fc",
    email: "rishi@swiggy.com",
    phone: "+91-99822-41122",
    linkedinUrl: "https://linkedin.com/in/rishimal",
    company: "Swiggy",
    companySize: "5,000–10,000",
    industry: "Food Tech",
    companyLocation: "Bangalore, India",
    status: "Qualified",
    pipeline: "Mid-Market",
    priority: "High",
    dealValue: 42000,
    currency: "USD",
    leadScore: 88,
    probability: 62,
    source: "Referral",
    channels: ["Email", "Phone"],
    lastActivityAt: new Date("2024-06-15"),
    nextFollowupAt: new Date("2024-06-18"),
    tags: ["High Intent", "Operations"],
    createdAt: new Date("2024-06-12"),
  },
  {
    id: "L003",
    firstName: "Jennifer",
    lastName: "Lee",
    name: "Jennifer Lee",
    avatar: "#fee2e2",
    email: "jennifer.lee@freshworks.com",
    phone: "+1-312-443-2290",
    linkedinUrl: "https://linkedin.com/in/jenniferlee",
    company: "Freshworks",
    companySize: "4,000–6,000",
    industry: "SaaS / CX",
    companyLocation: "Chennai, India",
    status: "Contacted",
    pipeline: "SaaS",
    priority: "Low",
    dealValue: 12000,
    currency: "USD",
    leadScore: 52,
    probability: 21,
    source: "Website Form",
    channels: ["Email"],
    lastActivityAt: new Date("2024-06-20"),
    nextFollowupAt: new Date("2024-06-25"),
    tags: ["Support Team", "CX"],
    createdAt: new Date("2024-06-19"),
  },
  {
    id: "L004",
    firstName: "Alex",
    lastName: "Turner",
    name: "Alex Turner",
    avatar: "#d9f99d",
    email: "alex.turner@airtable.com",
    phone: "+1-213-772-1121",
    linkedinUrl: "https://linkedin.com/in/alexturner",
    company: "Airtable",
    companySize: "1,000–2,000",
    industry: "SaaS / Collaboration",
    companyLocation: "Los Angeles, USA",
    status: "Negotiation",
    pipeline: "Enterprise",
    priority: "High",
    dealValue: 95000,
    currency: "USD",
    leadScore: 90,
    probability: 72,
    source: "Event – SaaStr",
    channels: ["In-Person", "Email"],
    lastActivityAt: new Date("2024-07-10"),
    nextFollowupAt: new Date("2024-07-12"),
    tags: ["Enterprise", "Collaboration"],
    createdAt: new Date("2024-07-05"),
  },
  {
    id: "L005",
    firstName: "Tara",
    lastName: "Sengupta",
    name: "Tara Sengupta",
    avatar: "#ede9fe",
    email: "tara.s@bigbasket.com",
    phone: "+91-90017-22119",
    linkedinUrl: "https://linkedin.com/in/taras",
    company: "BigBasket",
    companySize: "12,000–15,000",
    industry: "E-commerce / Grocery",
    companyLocation: "Bangalore, India",
    status: "Prospects",
    pipeline: "Retail",
    priority: "Medium",
    dealValue: 18000,
    currency: "USD",
    leadScore: 46,
    probability: 18,
    source: "Cold Email",
    channels: ["Email"],
    lastActivityAt: new Date("2024-05-30"),
    nextFollowupAt: new Date("2024-06-03"),
    tags: ["Retail", "Grocery"],
    createdAt: new Date("2024-05-29"),
  },
  {
    id: "L006",
    firstName: "Michael",
    lastName: "O'Connor",
    name: "Michael O'Connor",
    avatar: "#ffe4e6",
    email: "m.oconnor@tesla.com",
    phone: "+1-945-991-2211",
    linkedinUrl: "https://linkedin.com/in/michaeloc",
    company: "Tesla",
    companySize: "50,000+",
    industry: "Automotive / EV",
    companyLocation: "Austin, USA",
    status: "Proposal",
    pipeline: "Corporate",
    priority: "Critical",
    dealValue: 250000,
    currency: "USD",
    leadScore: 94,
    probability: 75,
    source: "LinkedIn DM",
    channels: ["LinkedIn", "Email"],
    lastActivityAt: new Date("2024-08-01"),
    nextFollowupAt: new Date("2024-08-03"),
    tags: ["EV", "Automation", "Corporate"],
    createdAt: new Date("2024-08-01"),
  },
  {
    id: "L007",
    firstName: "Sonal",
    lastName: "Jain",
    name: "Sonal Jain",
    avatar: "#fef3c7",
    email: "sonal.jain@zomato.com",
    phone: "+91-99122-18811",
    linkedinUrl: "https://linkedin.com/in/sonalj",
    company: "Zomato",
    companySize: "4,000–6,000",
    industry: "Food Tech",
    companyLocation: "Gurgaon, India",
    status: "Qualified",
    pipeline: "Operations",
    priority: "High",
    dealValue: 38000,
    currency: "USD",
    leadScore: 81,
    probability: 60,
    source: "Referral",
    channels: ["Phone"],
    lastActivityAt: new Date("2024-07-11"),
    nextFollowupAt: new Date("2024-07-15"),
    tags: ["Operations", "High Intent"],
    createdAt: new Date("2024-07-10"),
  },
  {
    id: "L008",
    firstName: "Evelyn",
    lastName: "Cruz",
    name: "Evelyn Cruz",
    avatar: "#fef08a",
    email: "evelyn.cruz@notion.so",
    phone: "+1-347-292-1110",
    linkedinUrl: "https://linkedin.com/in/evelyncruz",
    company: "Notion",
    companySize: "500–1,200",
    industry: "Productivity SaaS",
    companyLocation: "New York, USA",
    status: "Contacted",
    pipeline: "SaaS",
    priority: "Medium",
    dealValue: 30000,
    currency: "USD",
    leadScore: 60,
    probability: 30,
    source: "Website Chatbot",
    channels: ["Chat", "Email"],
    lastActivityAt: new Date("2024-06-10"),
    nextFollowupAt: new Date("2024-06-14"),
    tags: ["SaaS", "Productivity"],
    createdAt: new Date("2024-06-09"),
  },
  {
    id: "L009",
    firstName: "Arjun",
    lastName: "Verma",
    name: "Arjun Verma",
    avatar: "#a7f3d0",
    email: "arjun.verma@reliance.com",
    phone: "+91-98710-12311",
    linkedinUrl: "https://linkedin.com/in/arjunverma",
    company: "Reliance Retail",
    companySize: "200,000+",
    industry: "Retail / Ecommerce",
    companyLocation: "Mumbai, India",
    status: "Negotiation",
    pipeline: "Enterprise",
    priority: "Critical",
    dealValue: 175000,
    currency: "USD",
    leadScore: 92,
    probability: 70,
    source: "Partner Referral",
    channels: ["Phone", "Email"],
    lastActivityAt: new Date("2024-07-21"),
    nextFollowupAt: new Date("2024-07-25"),
    tags: ["Enterprise", "Retail"],
    createdAt: new Date("2024-07-18"),
  },
  {
    id: "L010",
    firstName: "Sarah",
    lastName: "Nguyen",
    name: "Sarah Nguyen",
    avatar: "#dbeafe",
    email: "sarah.nguyen@hubspot.com",
    phone: "+1-626-927-5511",
    linkedinUrl: "https://linkedin.com/in/sarahng",
    company: "HubSpot",
    companySize: "7,000–8,000",
    industry: "CRM / SaaS",
    companyLocation: "Boston, USA",
    status: "Prospects",
    pipeline: "Marketing Teams",
    priority: "Low",
    dealValue: 9000,
    currency: "USD",
    leadScore: 41,
    probability: 10,
    source: "Ad Campaign",
    channels: ["Email"],
    lastActivityAt: new Date("2024-05-10"),
    nextFollowupAt: new Date("2024-05-15"),
    tags: ["CRM", "Marketing"],
    createdAt: new Date("2024-05-09"),
  },
];
